### ISSUE TITLE
Player Stats

### ISSUE THREAD

**Issue by ashtonmths** [arnabsen1729/IPLStats#2]
Sorry for interupting but when i try to search a player it comes as Sorry Something went wrong. When i checked in heroku log i got this : 
TypeError: Cannot read property '0' of undefined
       at getPlayerStats (/app/src/dataFetch.js:58:35)
       at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by arnabsen1729** [comment]
Maybe the player name was wrong. The API that I used sometimes give the closest name, else sends a status 400. So what I did was put that part in a try catch block.

**Comment by ashtonmths** [comment]
Umm I tried to search KL Rahul as u did but no luck. Maybe I did something wrong? ![IMG_20201021_132027.jpg](https://user-images.githubusercontent.com/68967455/96689645-4ea40800-13a0-11eb-857a-9ae5e7e54628.jpg)

**Comment by arnabsen1729** [comment]
Not able to reproduce :cry: 
![image](https://user-images.githubusercontent.com/51032928/96689850-932fa380-13a0-11eb-933b-6ae87c05ee62.png)

**Comment by ashtonmths** [comment]
Is it because I changed prefix? Or does that function need a specific file?

**Comment by arnabsen1729** [comment]
That shouldn't be an issue

**Comment by ashtonmths** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/68967455/96692038-3b466c00-13a3-11eb-9418-7ef79e2a5d76.png)
![Screenshot (43)](https://user-images.githubusercontent.com/68967455/96692045-3d102f80-13a3-11eb-8228-b90345b2de92.png)

**Comment by ashtonmths** [comment]
Maybe there are some files missing to run that command? @arnabsen1729

**Comment by arnabsen1729** [comment]
okay, so you need to create an account in the https://www.cricapi.com/ and save the token in an env file, that token is used in calling the apis. I have made a [sample.env](https://github.com/arnabsen1729/IPLStats/blob/master/sample.env) file, you can try look at that.

**Comment by ashtonmths** [comment]
> okay, so you need to create an account in the https://www.cricapi.com/ and save the token in an env file, that token is used in calling the apis. I have made a [sample.env](https://github.com/arnabsen1729/IPLStats/blob/master/sample.env) file, you can try look at that. 

Okay. Can I leave discord bot token empty in sample.env for henroku??

**Comment by arnabsen1729** [comment]
sample.env is just a sample file for `.env` . You can directly put the Tokens and the API key in the code, but it is not considered a good practice, but yeah it will work.

**Comment by ashtonmths** [comment]
Thanks for the help again👍

**Comment by ashtonmths** [comment]
ummm sorry but its the same.........
![Screenshot (45)_LI](https://user-images.githubusercontent.com/68967455/96713576-70ac8300-13be-11eb-808a-e2e33270ac9b.jpg)
@arnabsen1729

**Comment by ashtonmths** [comment]
Any Breakthrough??
